### ISSUE TITLE
Incorrect times loaded for days

### ISSUE THREAD

**Issue by pippinsplugins** [RebelCodecom/edd-bookings#14] opened 2016-11-21 19:13 UTC
We're still seeing reports of the available time slots being wildly incorrect for some users.

Product configuration:
![screen shot 2016-11-21 at 1 11 06 pm](https://cloud.githubusercontent.com/assets/1034109/20496731/001fbf6a-afec-11e6-8076-1a6ee98585f3.png)

Live product: http://www.mmtarotreadings.com.au/sessions/tarot-card-reading-15-minutes/

Click through the days to see the time slots change irregularly. For example, Wednesday shows this:

![screen shot 2016-11-21 at 1 11 55 pm](https://cloud.githubusercontent.com/assets/1034109/20496763/1acf11bc-afec-11e6-8605-af98cef7a432.png)

Thursday is not even configured as an available slot yet it shows availability: 
![screen shot 2016-11-21 at 1 12 13 pm](https://cloud.githubusercontent.com/assets/1034109/20496793/3139d324-afec-11e6-8f23-ef8cc97951d9.png)

Can we please get this resolved finally? It's been problematic since the beginning.

**Comment by cklosowski** [comment] 2016-11-21 19:19
@pippinsplugins I think it's related to the issue I opened as well.

**Comment by cklosowski** [comment] 2016-11-21 19:19
#10 for cross reference.

**Comment by pippinsplugins** [comment] 2016-11-21 19:20
Ah yep, didn't see that one.

**Comment by mecha** [comment] 2016-11-23 08:57
Confirmed that the source of the problem is the same as the one mentioned in issue #10. Closing this issue as a duplicate.

**Closed by mecha** 2016-11-23 08:57 UTC
Labels: bug, duplicate
