### ISSUE TITLE
Availability issue, incorrectly listing days available

### ISSUE THREAD

**Issue by cklosowski** [RebelCodecom/edd-bookings#10] opened 2016-11-20 22:54 UTC
Here is my product configuration:
![screen shot 2016-11-20 at 3 50 44 pm](https://cloud.githubusercontent.com/assets/1390124/20466921/467b514e-af39-11e6-9b8c-594c6c1fba1d.png)

It's `Monday` from `16:00:00` to `18:00:00`

With the 1 hour slots I should have availability on Monday's only and two options, `16:00:00` and `17:00:00`, however, I'm getting the following availability:
Sunday: 17:00:00
Monday: 16:00:00

![screen shot 2016-11-20 at 3 51 03 pm](https://cloud.githubusercontent.com/assets/1390124/20466934/9bb1ebd2-af39-11e6-93ac-06017f18309c.png)

![screen shot 2016-11-20 at 3 51 08 pm](https://cloud.githubusercontent.com/assets/1390124/20466935/9f347784-af39-11e6-9eff-f9cd3e4245a1.png)

![screen shot 2016-11-20 at 3 51 14 pm](https://cloud.githubusercontent.com/assets/1390124/20466936/a21a3e02-af39-11e6-8f13-ccf15bbbe039.png)

I'm also getting a JS error when initially clicking the 'Purchase' button, before it shows the calendar.
`TypeError: Cannot read property 'hide' of undefined
 /wp-content/plugins/edd-bookings/assets/js/eddbk/widget/service-session-picker.js?ver=2.1.3:162`

My site is in GMT -7 (Arizona) and that's the timezone I'm in as well.

**Comment by mecha** [comment] 2016-11-21 08:49
Confirmed the bug on the latest version. Thanks!

**Comment by mecha** [comment] 2016-11-24 13:52
@cklosowski Submitted a PR that fixes this bug. If you're interested in testing it out let me know. Otherwise I'll just merge it in!

**Comment by cklosowski** [comment] 2016-11-29 17:02
@mecha, this seems to fix it for me. thanks.

**Comment by cklosowski** [comment] 2016-11-29 17:02
As a note, I still do see this JS error when clicking purchase:
`TypeError: Cannot read property 'hide' of undefined
 /wp-content/plugins/edd-bookings/assets/js/eddbk/widget/service-session-picker.js?ver=2.1.3:162`

**Comment by mecha** [comment] 2016-11-29 17:08
Glad to hear @cklosowski. I'll merge in the solution for the next release.

The JS error is unrelated and will be fixed in another issue targeted for the release after the next one.

**Comment by pippinsplugins** [comment] 2016-12-07 02:21
Re-opening. It's not working properly still.

Take a look, for example, at Monday of this site: 

Product configuration:
![screen shot 2016-12-06 at 8 20 30 pm](https://cloud.githubusercontent.com/assets/1034109/20952378/8e744806-bbf1-11e6-90d0-928dfb9b2460.png)

Calendar:
![screen shot 2016-12-06 at 8 21 26 pm](https://cloud.githubusercontent.com/assets/1034109/20952388/9751f27a-bbf1-11e6-9a5c-2e7182f6d039.png)

Notice how it should show `9:00` as an option but it doesn't. It starts at `10:00`.

**Comment by pippinsplugins** [comment] 2016-12-07 02:22
Full settings for product: 
![screen shot 2016-12-06 at 8 22 37 pm](https://cloud.githubusercontent.com/assets/1034109/20952411/bff339be-bbf1-11e6-8246-764cc31b5e43.png)

**Comment by markzahra** [comment] 2016-12-07 08:21
@pippinsplugins can you send us the whole bookings settings metabox please? I personally cannot reproduce the issue locally. Have you confirmed that there aren't any booked slots by any chance?

**Comment by mecha** [comment] 2016-12-07 09:36
@pippinsplugins I've tried using your settings on the currently released version (`2.1.3`) and got the same results. However, when using `2.2.0-RC1` everything worked as expected.

Can you confirm that the site is using the latest version's release candidate? You should be able to tell instantly - we've added an availability preview in this version 😊 

![image](https://cloud.githubusercontent.com/assets/5425482/20962262/f00d03a6-bc68-11e6-9ca0-3c20855bf463.png)

**Comment by pippinsplugins** [comment] 2016-12-07 20:59
@mecha Checking

**Comment by pippinsplugins** [comment] 2016-12-07 21:07
Ugh, appears they didn't actually update to RC1, just told me they did.

I've manually updated it for them and now dates appear to be working properly so all good here!

**Comment by markzahra** [comment] 2016-12-07 21:11
@pippinsplugins we thought something must have been off. Glad to hear that!

**Comment by pippinsplugins** [comment] 2016-12-07 22:17
Sorry folks, actually still doing weird things. Here's what they just said:

>>>Start times Mon-Fri should be 9:00
But when you select different days with a start time of 9:00 (Mondays, Tuesdays, Wednesdays, Fridays), it varies the start time between 9:00, 9:05, 9:10, 9:15 and 9:20 depending on which day you choose.

>>>And on Saturday when the start time is 8:30, it shows times varying between 8:30 and 8:50.

You can see that here http://www.mmtarotreadings.com.au/sessions/tarot-card-reading-15-minutes/

**Comment by markzahra** [comment] 2016-12-08 07:22
@pippinsplugins can you reproduce this on your own site?

And can we get login details for this site to compare all the settings please?

Reminder: Miguel is away till Tuesday of next week.

**Comment by pippinsplugins** [comment] 2016-12-08 15:41
Posting log in details on Trello since that's private.

**Closed** 2017-05-19 15:44 UTC
Labels: bug
